# Generated by Django 3.1.6 on 2021-02-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discrations',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
